spring.datasource.url=jdbc:mysql://localhost:3306/leafquery?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
spring.datasource.username=leafquery
spring.datasource.password=pzycPasax8Gbw5pe

app.upload.dir=/www/wwwroot/116.62.130.148/images/uploads
